# Generated by Django 4.1 on 2022-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_vahed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(choices=[('cs', 'علوم کامپیوتر'), ('ce', 'مهندسی کامپیوتر'), ('math', 'ریاضیات و کاربردها'), ('electric', 'برق'), ('mechanic', 'مکانیک'), ('civil', 'عمران'), ('aerospace', 'هوافضا')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(choices=[('aut', 'امیرکبیر'), ('sut', 'شریف'), ('ut', 'تهران')], db_index=True, max_length=64),
        ),
    ]
