# Generated by Django 4.1 on 2022-08-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy_vahed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='charts')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_vahed.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_vahed.university')),
            ],
        ),
    ]
