# Generated by Django 4.1 on 2022-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_vahed', '0002_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
